id: DE14D30E2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:00:56+00:00'
last_modified: '2022-05-27T15:04:49.676067+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    e3eb:
      image_group_id: I1PD95909
      title: བསྒོམ་པའི་རིམ་པ།
      total_pages: 1902
      order: 64
      base_file: e3eb.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
