id: P694C6999
initial_creation_type: ocr
source_metadata:
  volumes:
    d49397c0aadb4db3b06bae8e9d1c61d1:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བསྒོམ་པའི་རིམ་པ།
      total_pages: 1902
      volume_number: 64
