id: P694C6999
initial_creation_type: ocr
source_metadata:
  volumes:
    4601f415acfe4292a72ab4d1a3e31e12:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བསྒོམ་པའི་རིམ་པ།
      total_pages: 1902
      volume_number: 64
